### ISSUE TITLE
New Error Never Saw before

### ISSUE THREAD

**Issue by Khaledmohamed1988** [0xSolanaceae/proXXy#19]
hello
i was using old version of the proxy scraper since 2023 but cant remember the version exactly its the one before 2.4 might be
1 version down , lately i reinstall my windows and installed everything again and installed the requirements inside the folder
but 1st time to see error like this from hrequests no idea if it comes from the library itself or the code need tweaks to deal with that
its already scraped proxies rightly after but this error suppose to not be here should be fixed might its affect something else
i cant decide , the checking from your side developer will put things on the right side
sorry for disturb and thanks again hope i got reply soon and fix its really annoying thank you
here you are printscreen of the error
![image](https://github.com/Atropa-Solanaceae/proXXy/assets/111654257/3d3d2367-0a6c-4dde-802a-cb5f80806580)

**Comment by Atropa-Solanaceae** [comment]
this should now be fixed
